version: '3.7'

services:
  aiservice:
    volumes:
      - ./aiservice/uwsgi.ini:/uwsgi.ini
  pfft:
    hostname: pfft
  gateway:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /certs:/etc/nginx/ssl:ro