version: '3.7'

services:
  aiservice:
    volumes:
      - ./aiservice/uwsgi.ini:/uwsgi.ini
  pfft:
    hostname: pfft
  gateway:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /ssl_data:/etc/resty-auto-ssl
      - ./nginx.conf:/etc/nginx/pfft.conf
      - ./certbot/www:/var/www/certbot/:ro
      - /certbot/conf:/etc/nginx/ssl/:ro
      - /etc/letsencrypt/live/pfft.bilalanjum.me/fullchain.pem:/etc/letsencrypt/live/pfft.bilalanjum.me/fullchain.pem
      - /etc/letsencrypt/live/pfft.bilalanjum.me/privkey.pem:/etc/letsencrypt/live/pfft.bilalanjum.me/privkey.pem
  certbot:
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw