version: '3.7'

services:
  aiservice:
    build:
      context: ./aiservice
      dockerfile: Dockerfile
    container_name: aiservice
    restart: "unless-stopped"
    networks:
      - backend
  pfft:
    build:
      context: ./pfft
      dockerfile: Dockerfile
    container_name: pfft
    restart: "unless-stopped"
    networks:
      - backend
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: gateway
    restart: "unless-stopped"
    depends_on:
      - aiservice
      - pfft
    networks:
      - backend
    volumes:
      - /etc/letsencrypt/archive/pfft.ai:/etc/letsencrypt/archive/pfft.ai

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
