version: '3.7'

services:
  aiservice:
    volumes:
      - ./aiservice/uwsgi.ini:/uwsgi.ini
  pfft:
    hostname: pfft
  gateway:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email heymitin@gmail.com -d pfft.ai --agree-tos